# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=hoot

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# S3 / LocalStack
app.s3.endpoint=http://localhost:4566
app.s3.bucket=produtos

# Application context
server.servlet.context-path=/spa

# Port
server.port=8080

# Optional
spring.jpa.open-in-view=false