# =========================
# PostgreSQL Database
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/api-pedido
spring.datasource.username=postgres
spring.datasource.password=hoot
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Flyway
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# =========================
# S3 / LocalStack
# =========================
app.s3.endpoint=http://localhost:4566
app.s3.bucket=produtos

# =========================
# Server
# =========================
server.port=8080

# =========================
# Optional
# =========================
spring.jpa.open-in-view=false

debug=true